services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
      env_file:
        - .env
      volumes:
        - .:/app
        - /app/node_modules
      command: npm run dev
      ports:
        - "3000:3000"
      depends_on:
        - postgres
        - redis
    redis:
      image: redis:lastest
      ports:
        - "6379:6379"
      volumes:
        - redis:/data
    postgres:
      image: postgres:lastest
      restart: always
      env_file:
        - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
volumes:
  pgdata:
  redis:
    driver: local